# Generated by Django 5.0.6 on 2024-06-23 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envio',
            name='destinatario',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='envio',
            name='remitente',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='envio',
            name='valor_declarado',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='PerfilUsuario',
        ),
    ]
